### ISSUE TITLE
Loyalty property for planeswalker

### ISSUE THREAD

**Issue by thamindzzeye** [MagicTheGathering/mtg-sdk-swift#2]
I see that loyalty is commented out in the Card object, how do i get a planeswalkers loyalty??

**Comment by thamindzzeye** [comment]
This is kind of a show stopper, because some attributes are missing, I am going to remove this sdk from my app and build my own rest client with JSON parsing, and an object factory.

Hope this is resolved soon.

**Comment by rpcarson** [comment]
@thamindzzeye hey! thanks for raising this issue. I'm looking at the framework in order to improve it/update it and I will fix this issue while I'm doing that. I cant give an estimate on when these things will be done given my current schedule but I will try to get it done this weekend

**Comment by thamindzzeye** [comment]
no worries mate, I ended up creating my own classes and removing the framework. 
Im sure other will appreciate it though. Also great work!

**Comment by intere** [comment]
This issue is Addressed by https://github.com/MagicTheGathering/mtg-sdk-swift/pull/9

**Comment by intere** [comment]
@thamindzzeye - this is now addressed by #9 - could you please verify and close this issue?
Please note: there is even a parsing test for that field: https://github.com/MagicTheGathering/mtg-sdk-swift/blob/master/MTGSDKSwiftTests/ParserTests.swift#L30-L32
