### ISSUE TITLE
Update pod version

### ISSUE THREAD

**Issue by vcoutasso** [MagicTheGathering/mtg-sdk-swift#22]
The latest version of MTGSDKSwift on Cocoapods seems to be v1.0 according to [the website](https://cocoapods.org/pods/MTGSDKSwift), which is already 3 years old.  

Since v1.1 is already a few months old, it might be a good idea to update the pod version to include the latest changes.

**Comment by chorizo3nfeugo** [comment]
> The latest version of MTGSDKSwift on Cocoapods seems to be v1.0 according to [the website](https://cocoapods.org/pods/MTGSDKSwift), which is already 3 years old.
> 
> Since v1.1 is already a few months old, it might be a good idea to update the pod version to include the latest changes.

Yes please! I just tried to install this via cocoa pods and it didn't completely work here.  Running Xcode 12.4 and latest cocoa pods here.

**Comment by rpcarson** [comment]
ok! i will take a look

**Comment by rpcarson** [comment]
1.1 is out, thanks everyone
